# Generated by Django 5.2.9 on 2025-12-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunovalido',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disciplinavalida',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
