# Generated by Django 5.2.9 on 2026-01-08 00:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alunovalido_nome_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField()),
                ('motivo', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes', to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Suspensão de Aluno',
                'verbose_name_plural': 'Suspensões de Alunos',
            },
        ),
    ]
