# Generated by Django 5.2.9 on 2026-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_suspensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatendimento',
            name='local',
            field=models.CharField(default='A definir', max_length=100, verbose_name='Local da Monitoria'),
        ),
    ]
